### ISSUE TITLE
VATZ CLI commands Managements

### ISSUE THREAD

**Issue by rootwarp** [dsrvlabs/vatz#107]
- Related: #178 

---

## Checklist
- [x] New Feature for the SVC/Plugin
- [ ] New Feature for CI/CD
- [ ] Enhancement on Vatz
- [ ] Others(etc. e.g, documentation,...)
---

### **Please describe, what it's about or related Problem with**
> A clear description of what feature need to be developed or enhanced in Vatz 

As you know, `cobra` package based CLI feature is usually used on blockchain nodes.
So, applying `cobra` package will make `vatz` project more familiar and more useful
because new types of feature and options can be applied easy.

After develop this feature, start command of `vatz` will be like below.

```
~$ vatz start --config near.yaml
```

### **Describe the output that you are expecting for above**
> A clear and concise description of what you expect to happen.

Not related output stuff.

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

Use `flag` package to accept custom options.

### TODOs by Q3
- [x] Convert this issue to `good first issue` for CLI  
- [x] List up CLI command list up basic Command list VATZ
- [x] Create a documents for VATZ CLI 

---

# Child Issues
- #202
