### ISSUE TITLE
Refactoring to remove "interface" types

### ISSUE THREAD

**Issue by rootwarp** [dsrvlabs/vatz#125]
## Checklist
- [ ] New Feature for the SVC/Plugin
- [ ] New Feature for CI/CD
- [X] Enhancement on Vatz
- [ ] Others(etc. e.g, documentation,...)
---

### **Please describe, what it's about or related Problem with**
> A clear description of what feature need to be developed or enhanced in Vatz 

`interface` type is using too much all of the code base.
But it could be serious problem in near future because,
- This means source code is not self-documented. Developer can't understand code easily if variables are defined as interface type
- interface type can be broken in runtime. We should test really hard by checking every possible values.
- And that means development pace will be slow down.

### **Describe the output that you are expecting for above**
> A clear and concise description of what you expect to happen.

Avoid to use `interface` type if possible.

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

This refactoring task will be huge job and also will be affected to other tasks that are on going.
So I suggest do refactoring task by module one by one.

### **Additional context**
> Add any other context or screenshots about the feature request here.

---

### Child issues.
- [x] #179
- [x] #181
- [x] #203
