### ISSUE TITLE
Plugin Development : SystemUtil

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#242]
- Parents: #241
- Related: #225 
---

## Checklist

- [x] New Feature for the Service/Plugin (Vatz)
- [ ] Enhancement (Vatz)
- [ ] others(etc. e.g, documentation, project policy management)

---
### **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. such as Ex. I'm always frustrated

### **Describe the solution you'd like| Ex**
> A clear and concise description of what you want to happen

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you have considered.

### **Additional context or comment**
> Add any other context or screenshots about the feature request here.

## Child issues
- [x] #249
- [x] #295
- [x] #305
- [x] https://github.com/dsrvlabs/vatz/issues/423

**Comment by heejin-github** [comment]
## 2022-12-28
- RC : https://github.com/dsrvlabs/vatz-plugin-sysutil/commit/376a7f28bf1a55be1c21d3103c1fce6d9af96471

**Comment by heejin-github** [comment]
## 2022-01-06
- v1.0-beta release : https://github.com/dsrvlabs/vatz-plugin-sysutil/releases/tag/v1.0-beta

**Comment by xellos00** [comment]
@heejin-github 
I moved this issue to big-chink miles stone which isn't always comes with bi-weekly Sprint.

**Comment by xellos00** [comment]
@heejin-github 
is there anything that you think we need to develop more? 
Can you close this issue if there's no extra developments?

**Comment by heejin-github** [comment]
> @heejin-github 
> is there anything that you think we need to develop more? 
> Can you close this issue if there's no extra developments?  

OK, Close this issue.
