### ISSUE TITLE
V2 VATZ Projects Milestone

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#493]
## Checklist
- [ ] New Feature for the SVC/Plugin
- [ ] New Feature for CI/CD
- [x] Enhancement on Vatz
- [ ] Others(etc. e.g, documentation,...)
---

### **Please describe, what it's about or related Problem with**
> A clear description of what feature need to be developed or enhanced in Vatz 

- POC is over, and VATZ's was too much tended to target or focused on monitoring. As discussed when we started the project at first, it's time to revert back to develop the initially designed product.
   - VATZ is only responsible for relaying all plug-ins 
   - Even the behaviors such as sending notification or monitoring has to be handled by plug-in.

### **Describe the output that you are expecting for above**
> A clear and concise description of what you expect to happen.

As mentioned above, architecture design has to be redesigned to revert back to first time that we started our project and then its design need to shared and discussed.
Here's a link, update after research whether we can doable or not. 
- [V1 Architecture Link](https://drive.google.com/file/d/1PMmA4uO8iP-z4sC24kXAvRz1_H1m6zhH/view?usp=sharing)
- [V2 Architecture Link](https://drive.google.com/file/d/1yMwm1_XjU6WKIdLlcU6nFLyTM3r6pHJh/view?usp=sharing)
   -  https://github.com/dsrvlabs/vatz/discussions/510#discussioncomment-7376673 

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

### **Additional context**
> Add any other context or screenshots about the feature request here.

---

## Child Issues
- [ ] #495

**Comment by xellos00** [comment]
- https://github.com/dsrvlabs/vatz/discussions/510#discussioncomment-7376673

**Comment by xellos00** [comment]
@xellos00 , @rootwarp 

To DOs: 
- 1. Move code to VATZ:
    - 1. Repo(VATZ-proto): 
       -  Branch name: V2-pilot
    - 2. Repo(VATZ): 
       - Branch name:  V2-pilot
    - 3. Repo(VATZ-plugin) repo new: 
       - @rootwarp, Create any repo but make it public, please. 
        
- 2. Build Rest service that's left over
   - @xellos00  
       - [ ] marshaling & unmashaling
       - [ ] in & output (shaping code components)  
            - will discuss with @rootwarp 
   - @rootwarp 
      - [ ] finish request relayer 
      - [ ] service end point

**Comment by xellos00** [comment]
@rootwarp 
Can you upload all the works on  a new branches on VATZ-proto, VATZ with `v2-pilot`, and new v2 pilot plugin?

**Comment by rootwarp** [comment]
> @rootwarp Can you upload all the works on a new branches on VATZ-proto, VATZ with `v2-pilot`, and new v2 pilot plugin?

Sorry I'm late.
I will push all of them before today's meeting.

**Comment by xellos00** [comment]
> > @rootwarp Can you upload all the works on a new branches on VATZ-proto, VATZ with `v2-pilot`, and new v2 pilot plugin?
> 
> Sorry I'm late. I will push all of them before today's meeting.

No worry, you don't have to, take your time and ping me when you do

**Comment by rootwarp** [comment]
@xellos00 New codes are pushed
- proto: https://github.com/dsrvlabs/vatz-proto/tree/v2-pilot
- engine(agent): https://github.com/dsrvlabs/vatz/tree/v2-pilot
- plugin(tester): https://github.com/dsrvlabs/vatz-v2-engine-tester/tree/v2-pilot

**Comment by rootwarp** [comment]
@xellos00 I'm defining interfaces for communicating between modules, but I got some another idea of direction of architecture. 
What do you think implementing "handler" and "relayer" as an independent gRPC services?

**Comment by xellos00** [comment]
> @xellos00 I'm defining interfaces for communicating between modules, but I got some another idea of direction of architecture. What do you think implementing "handler" and "relayer" as an independent gRPC services?

@rootwarp 
Thanks for update!!
let me ping you tomorrow. I think I need to understand your idea because concept of hander & relayer may different from each other.

**Comment by xellos00** [comment]
- END Point SVC
- Relayer SVC
- Handler SVC
- Registration SVC

--- 

# Light version 
1. VATZ 뜰때 4개를 한꺼번에 띄운다. 
   - VATZ를 하나 띄우면 그 안에서 4개의 go Routine이 돌아간다.  

# Official version 
1. 위의 light 버전을 개발하다가 정식으로 마이크로 서비스로 전환을 기획 중
