### ISSUE TITLE
Vatz Document Managements

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#97]
## Checklist

- [ ] New Feature for the Service/Plugin (Vatz)
- [ ] Enhancement (Vatz)
- [X] others(etcm ie, documentation)

---

### TODOs:

- [x] 1. Vatz Project Intension #150
- [x] 2. Vatz Project Design #151 
- [x] 3. Blueprint 
- [x] 4. Project Management Strategy
   - [x] 4.1. PR Policy #96
   - [x] 4.2. Validator agile Process   #149 

---

# Child Issues
- https://github.com/dsrvlabs/vatz/issues/89
- https://github.com/dsrvlabs/vatz/issues/94
- #96 
- #149
- #150
- #151
- #175 
- #176
